repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
      - id: black
        args: [--quiet]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        files: "sunsynk/.*.py"
        args:
          - -L
          - HASS,hass,Hass
          - --skip
          - "package-lock.json,*.map,www/docs/.vitepress/cache/*"
      - id: codespell
        files: "hass-addon-sunsynk-multi/.*.py"
        args:
          - -L
          - HASS,hass,Hass
          - --skip
          - "package-lock.json,*.map,www/docs/.vitepress/cache/*"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
      - id: mypy
        files: "^(sunsynk|hass-addon-multi)/"
        additional_dependencies:
          ["types-attrs", "attrs>21", "types-PyYAML", "pymodbus"]
      - id: mypy
        files: "hass-addon-multi/.*.py"
        additional_dependencies:
          ["types-attrs", "attrs>21", "types-PyYAML", "pymodbus"]
