# https://github.com/home-assistant/docker-base
build_from:
  aarch64: "homeassistant/aarch64-base-python:3.12-alpine3.21"
  amd64: "homeassistant/amd64-base-python:3.12-alpine3.21"
  armhf: "homeassistant/armhf-base-python:3.12-alpine3.21"
  armv7: "homeassistant/armv7-base-python:3.12-alpine3.21"
  i386: "homeassistant/i386-base-python:3.12-alpine3.21"
