name: Deploy sunsynk addon to ghcr.io

on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
  workflow_dispatch: {}

jobs:
  deployer:
    uses: kellerza/hass-addons/.github/workflows/deployer.yml@main
    secrets: inherit
    with:
      addon-slug: hass-addon-sunsynk-multi
      addon-slug-edge: hass-addon-sunsynk-edge
      pkg-name: sunsynk
      registry-image: ghcr.io/${{ github.repository_owner }}/hass-addon-sunsynk-multi
